### ISSUE TITLE
Importing from a subfolder to a parent within a subfolder has the incorrect import

### ISSUE THREAD

**Issue by starkevin** [starkevin/VSCode-TypeScript-Importer#2]
**ES6/CommonJS only**

When importing a class that is exposed 2 or more levels down, but is then contained within subfolders, the path placed into the import statement is incorrect.

```
import { CoinLookup } from "./../util../CoinLookup";
```

**Comment by starkevin** [comment]
Should be

```
import { CoinLookup } from "./../../util/CoinLookup";
```

**Comment by starkevin** [comment]
Note that this only affects when you're 2 or more level deep.

**Comment by another-guy** [comment]
My teammate and I observe that behavior too. For now, it's still easier to remove the fix the path than type the entire thing manually. Nice plugin!
Looking forward to seeing an update that fixes the bug.

**Comment by starkevin** [comment]
@another-guy this is now fixed
