### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by lucap86** [starkevin/VSCode-TypeScript-Importer#4]
With Code Version 1.10.2 (1.10.2)
After install both Extensions Market and vsix from this github, Code autocomplete is disabled and plugin doesn't work
If i uninstall it code autocomplete feature works again

Is this a common issue?

**Comment by starkevin** [comment]
What do you mean autocomplete doesn't work sorry?

**Comment by lucap86** [comment]
When plugin is installed and active Vs code intellisense doesn't work. Furthermore no plugin import work anymore

**Comment by starkevin** [comment]
Can you provide a sample project where this happens?
